### ISSUE TITLE
How to deal with Bony Fish?

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/country-reports#16]
Bony fish used to be defined by:

1. Sarcopterygii  https://www.gbif.org/species/238
2. Actinopterygii https://www.gbif.org/species/204

It seems there are no higher taxon below Chordata that defines Bony Fish anymore because we haven´t got [Osteichthyes](https://www.catalogueoflife.org/data/taxon/8VVWB) in the backbone.

So i guess we would need backbone keys for the [122](https://www.catalogueoflife.org/data/search?TAXON_ID=8VVWB&rank=order&status=accepted&status=provisionally%20accepted) orders sitting under Osteichthyes in COL?

@mdoering would such a list of orderKeys be easy for you to generate?

**Comment by mdoering** [comment]
Thats terrible. We might have other families from non COL sources which are not included in those 122 orders.
And Osteichthyes is not pointing to fish only, but also includes all birds:
Osteichthyes > Sarcopterygii > Tetrapoda > Amniota > Aves
https://www.catalogueoflife.org/data/taxon/MB

Here is the list of orders under [Sarcopterygii](https://www.catalogueoflife.org/data/taxon/8VSMX) as in COL AC22 which we used for the backbone:
https://api.checklistbank.org/dataset/9837/export.txt?rank=order&taxonID=8VSMX

and for [Actinopterygii](https://www.catalogueoflife.org/data/taxon/8VR36):
https://api.checklistbank.org/dataset/9837/export.txt?rank=order&taxonID=8VR36

We can generate the matching GBIF keys with the matching tools.
Is that what you need?

**Comment by mdoering** [comment]
[fish-orders.csv](https://github.com/gbif/country-reports/files/10153786/fish-orders.csv)

**Comment by mdoering** [comment]
[fish-orders-matched.csv](https://github.com/gbif/country-reports/files/10153792/fish-orders-matched.csv)

**Comment by thomasstjerne** [comment]
Thanks Markus - this will work

**Comment by thomasstjerne** [comment]
The [count for Bony Fish drops slightly](https://www.gbif.org/occurrence/search?country=DK&taxon_key=1103&taxon_key=1104&taxon_key=494&taxon_key=495&taxon_key=1105&taxon_key=496&taxon_key=497&taxon_key=1106&taxon_key=498&taxon_key=499&taxon_key=1107&taxon_key=537&taxon_key=538&taxon_key=1153&taxon_key=547&taxon_key=1162&taxon_key=548&taxon_key=549&taxon_key=550&taxon_key=1163&taxon_key=1164&taxon_key=1165&taxon_key=1166&taxon_key=1167&taxon_key=1305&taxon_key=1067&taxon_key=1306&taxon_key=1307&taxon_key=1308&taxon_key=1068&taxon_key=1069&taxon_key=587&taxon_key=1310&taxon_key=588&taxon_key=589&taxon_key=1311&taxon_key=1312&taxon_key=1313&taxon_key=590&taxon_key=708&taxon_key=890&taxon_key=774&taxon_key=889&taxon_key=773&taxon_key=772&taxon_key=888&taxon_key=765&taxon_key=879&occurrence_status=present) compared to to the [current report](https://www.gbif.org/sites/default/files/gbif_analytics/country/DK/GBIF_CountryReport_DK.pdf)  when this list of orders replaces the former two taxonKeys. So I suspect we miss a few orders in this list:

  | Acipenseriformes | Acipenseriformes | 1103 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Acipenseriformes |   |   |   | Acipenseriformes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Albuliformes | Albuliformes | 1104 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Albuliformes |   |   |   | Albuliformes
  | Amiiformes | Amiiformes | 494 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Amiiformes |   |   |   | Amiiformes
  | Anguilliformes | Anguilliformes | 495 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Anguilliformes |   |   |   | Anguilliformes
  | Ateleopodiformes | Ateleopodiformes | 1105 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Ateleopodiformes |   |   |   | Ateleopodiformes
  | Atheriniformes | Atheriniformes | 496 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Atheriniformes |   |   |   | Atheriniformes
  | Aulopiformes | Aulopiformes | 497 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Aulopiformes |   |   |   | Aulopiformes
  | Batrachoidiformes | Batrachoidiformes | 1106 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Batrachoidiformes |   |   |   | Batrachoidiformes
  | Beloniformes | Beloniformes | 498 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Beloniformes |   |   |   | Beloniformes
  | Beryciformes | Beryciformes | 499 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Beryciformes |   |   |   | Beryciformes
  | Cetomimiformes | Cetomimiformes | 1107 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Cetomimiformes |   |   |   | Cetomimiformes
  | Characiformes | Characiformes | 537 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Characiformes |   |   |   | Characiformes
  | Clupeiformes | Clupeiformes | 538 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Clupeiformes |   |   |   | Clupeiformes
  | Cypriniformes | Cypriniformes | 1153 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Cypriniformes |   |   |   | Cypriniformes
  | Cyprinodontiformes | Cyprinodontiformes | 547 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Cyprinodontiformes |   |   |   | Cyprinodontiformes
  | Elopiformes | Elopiformes | 1162 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Elopiformes |   |   |   | Elopiformes
  | Esociformes | Esociformes | 548 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Esociformes |   |   |   | Esociformes
  | Gadiformes | Gadiformes | 549 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Gadiformes |   |   |   | Gadiformes
  | Gasterosteiformes | Gasterosteiformes | 550 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Gasterosteiformes |   |   |   | Gasterosteiformes
  | Gobiesociformes | Gobiesociformes | 1163 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Gobiesociformes |   |   |   | Gobiesociformes
  | Gonorynchiformes | Gonorynchiformes | 1164 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Gonorynchiformes |   |   |   | Gonorynchiformes
  | Gymnotiformes | Gymnotiformes | 1165 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Gymnotiformes |   |   |   | Gymnotiformes
  | Lampriformes | Lampriformes | 1166 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Lampriformes |   |   |   | Lampriformes
  | Lepisosteiformes | Lepisosteiformes | 1167 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Lepisosteiformes |   |   |   | Lepisosteiformes
  | Lophiiformes | Lophiiformes | 1305 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Lophiiformes |   |   |   | Lophiiformes
  | Mugiliformes | Mugiliformes | 1067 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Mugiliformes |   |   |   | Mugiliformes
  | Myctophiformes | Myctophiformes | 1306 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Myctophiformes |   |   |   | Myctophiformes
  | Notacanthiformes | Notacanthiformes | 1307 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Notacanthiformes |   |   |   | Notacanthiformes
  | Ophidiiformes | Ophidiiformes | 1308 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Ophidiiformes |   |   |   | Ophidiiformes
  | Osmeriformes | Osmeriformes | 1068 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Osmeriformes |   |   |   | Osmeriformes
  | Osteoglossiformes | Osteoglossiformes | 1069 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Osteoglossiformes |   |   |   | Osteoglossiformes
  | Perciformes | Perciformes | 587 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Perciformes |   |   |   | Perciformes
  | Percopsiformes | Percopsiformes | 1310 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Percopsiformes |   |   |   | Percopsiformes
  | Pleuronectiformes | Pleuronectiformes | 588 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Pleuronectiformes |   |   |   | Pleuronectiformes
  | Polymixiiformes | Polymixiiformes | 589 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Polymixiiformes |   |   |   | Polymixiiformes
  | Polypteriformes | Polypteriformes | 1311 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Polypteriformes |   |   |   | Polypteriformes
  | Saccopharyngiformes | Saccopharyngiformes | 1312 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Saccopharyngiformes |   |   |   | Saccopharyngiformes
  | Salmoniformes | Salmoniformes | 1313 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Salmoniformes |   |   |   | Salmoniformes
  | Scorpaeniformes | Scorpaeniformes | 590 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Scorpaeniformes |   |   |   | Scorpaeniformes
  | Siluriformes | Siluriformes | 708 | HIGHERRANK | 95 | ACCEPTED | ORDER | Animalia | Chordata |   | Siluriformes |   |   |   | Siluriformes
  | Stephanoberyciformes | Stephanoberyciformes | 890 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Stephanoberyciformes |   |   |   | Stephanoberyciformes
  | Stomiiformes | Stomiiformes | 774 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Stomiiformes |   |   |   | Stomiiformes
  | Synbranchiformes | Synbranchiformes | 889 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Synbranchiformes |   |   |   | Synbranchiformes
  | Syngnathiformes | Syngnathiformes | 773 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Syngnathiformes |   |   |   | Syngnathiformes
  | Tetraodontiformes | Tetraodontiformes | 772 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Tetraodontiformes |   |   |   | Tetraodontiformes
  | Zeiformes | Zeiformes | 888 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata |   | Zeiformes |   |   |   | Zeiformes
  | Coelacanthiformes | Coelacanthiformes | 765 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata | Coelacanthi | Coelacanthiformes |   |   |   | Coelacanthiformes
  | Ceratodontiformes | Ceratodontiformes | 879 | EXACT | 96 | ACCEPTED | ORDER | Animalia | Chordata | Dipneusti | Ceratodontiformes |   |   |   | Ceratodontiformes
